#!/usr/bin/env bash
# autoinstall-usb/lib/grub.sh
#
# Project-owned GRUB UEFI configuration generation. The plan requires that we
# never trust an unmodified loader/config copied verbatim from the source
# ISO: EFI/BOOT/grub.cfg is always regenerated by this project so kernel
# arguments (tce=, backup=, waitusb=) and the boot menu are deterministic
# regardless of which Tiny Core ISO was used to seed the ESP.
#
# shellcheck shell=bash

# detect_tc_boot_files ESP_ROOT
# Prints "KERNEL|INITRD" (paths relative to the ESP root) or returns 1.
detect_tc_boot_files() {
  local esp_root="$1"
  local k="" i=""

  [[ -f "$esp_root/boot/vmlinuz64" ]] && k="/boot/vmlinuz64"
  [[ -z "$k" && -f "$esp_root/boot/vmlinuz" ]] && k="/boot/vmlinuz"
  if [[ -z "$k" ]]; then
    local found
    found="$(find "$esp_root/boot" -maxdepth 1 -type f -name 'vmlinuz*' 2>/dev/null | head -n1 || true)"
    [[ -n "$found" ]] && k="/boot/$(basename "$found")"
  fi

  for cand in corepure64.gz coreplus.gz core.gz tinycore.gz; do
    if [[ -f "$esp_root/boot/$cand" ]]; then
      i="/boot/$cand"
      break
    fi
  done
  if [[ -z "$i" ]]; then
    local foundi
    foundi="$(find "$esp_root/boot" -maxdepth 1 -type f -name '*.gz' 2>/dev/null | head -n1 || true)"
    [[ -n "$foundi" ]] && i="/boot/$(basename "$foundi")"
  fi

  [[ -n "$k" && -n "$i" ]] || return 1
  echo "$k|$i"
}

# render_grub_cfg ESP_UUID DATA_UUID KERNEL INITRD
# Prints the full grub.cfg content to stdout. Kept as a pure function
# (no filesystem writes) so it can be unit-tested by diffing the output.
#
# Entries:
#   1. Normal Tiny Core boot: tce=/backup=/waitusb= karg set, quiet.
#   2. Diagnostic Tiny Core boot: same persistence args, verbose logging.
#   3. Reserved Ubuntu autoinstall entry (Phase 3): only shown once
#      Phase 3 populates /ubuntu/casper/{vmlinuz,initrd} on the ESP, so the
#      menu never offers a boot target that cannot work yet.
render_grub_cfg() {
  local esp_uuid="$1" data_uuid="$2" kernel="$3" initrd="$4"
  cat <<EOF
set timeout=5
set default=0

menuentry "Tiny Core autoprov (normal)" {
  insmod part_gpt
  insmod fat
  search --no-floppy --fs-uuid --set=root ${esp_uuid}
  linux  ${kernel} quiet waitusb=20:UUID=${data_uuid} tce=UUID=${data_uuid} backup=UUID=${data_uuid}
  initrd ${initrd}
}

menuentry "Tiny Core autoprov (diagnostic, verbose)" {
  insmod part_gpt
  insmod fat
  search --no-floppy --fs-uuid --set=root ${esp_uuid}
  linux  ${kernel} waitusb=20:UUID=${data_uuid} tce=UUID=${data_uuid} backup=UUID=${data_uuid} loglevel=8 tc_verbose=1
  initrd ${initrd}
}

if [ -f (\$root)/ubuntu/casper/vmlinuz -a -f (\$root)/ubuntu/casper/initrd ]; then
  menuentry "Ubuntu Server autoinstall (reserved, Phase 3)" {
    insmod part_gpt
    insmod fat
    search --no-floppy --fs-uuid --set=root ${esp_uuid}
    linux  /ubuntu/casper/vmlinuz autoinstall ds=nocloud\;s=/ubuntu/nocloud/ ---
    initrd /ubuntu/casper/initrd
  }
fi
EOF
}

# generate_grub_uefi_loader ESP_ROOT ESP_UUID DATA_UUID
# Writes EFI/BOOT/grub.cfg and builds EFI/BOOT/BOOTX64.EFI with
# grub-mkstandalone (always regenerated; never trusts an ISO-provided
# BOOTX64.EFI).
generate_grub_uefi_loader() {
  local esp_root="$1" esp_uuid="$2" data_uuid="$3"

  have grub-mkstandalone || die "grub-mkstandalone not found. Install: sudo apt install grub-efi-amd64-bin"

  local bi
  bi="$(detect_tc_boot_files "$esp_root" || true)"
  [[ -n "$bi" ]] || die "Cannot detect TinyCore boot files under /boot (need vmlinuz* and *.gz)"
  local kernel="${bi%%|*}"
  local initrd="${bi##*|}"

  mkdir -p "$esp_root/EFI/BOOT"
  render_grub_cfg "$esp_uuid" "$data_uuid" "$kernel" "$initrd" >"$esp_root/EFI/BOOT/grub.cfg"

  echo "[+] Generating EFI/BOOT/BOOTX64.EFI with grub-mkstandalone (project-owned config)..."
  grub-mkstandalone \
    -O x86_64-efi \
    -o "$esp_root/EFI/BOOT/BOOTX64.EFI" \
    "boot/grub/grub.cfg=$esp_root/EFI/BOOT/grub.cfg" >/dev/null

  [[ -f "$esp_root/EFI/BOOT/BOOTX64.EFI" ]] || die "Failed to generate BOOTX64.EFI"
}
