#!/bin/sh
# /etc/init.d/autoprov - run provisioning at boot
# TinyCore init scripts style

TCE_DIR="/etc/sysconfig/tcedir"
STATE="$TCE_DIR/state"
LOGDIR="$TCE_DIR/logs"

start() {
  mkdir -p "$STATE" "$LOGDIR"

  echo "$(date -Iseconds) START" > "$STATE/autorun.started"

  if [ -x /opt/autorun/autoprov-run.sh ]; then
    /opt/autorun/autoprov-run.sh >>"$LOGDIR/autoprov.log" 2>&1
    rc=$?
  else
    echo "Missing /opt/autorun/autoprov-run.sh" >>"$LOGDIR/autoprov.log"
    rc=127
  fi

  echo "$(date -Iseconds) END rc=$rc" > "$STATE/autorun.finished"
  return $rc
}

case "$1" in
  start) start ;;
  *) exit 0 ;;
esac
